# Generated by Django 3.2.4 on 2022-03-01 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RentModel",
            fields=[
                ("uid", models.AutoField(primary_key=True, serialize=False)),
                ("tool_name", models.CharField(blank=True, max_length=500)),
                ("owner_name", models.CharField(blank=True, max_length=500)),
                ("contact_number", models.CharField(blank=True, max_length=500)),
                ("email_id", models.EmailField(blank=True, max_length=254)),
                ("tool_description", models.CharField(blank=True, max_length=150)),
                ("rent_price", models.FloatField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
